
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tapadvisor_development
  username: stuartsewell
  password:
  database: db/tapadvisor_development

test:
  <<: *default
  database: tapadvisor_test
  username: stuartsewell
  password:
  database: db/tapadvisor_development

production:
  <<: *default
  database: tapadvisor_production
  username: tapadvisor
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
